name: Etapa 0 # Iniciar Exercício

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_1_FILE: ".github/steps/1-assign.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Iniciar Exercício
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.6.0
    with:
      exercise-title: "Expanda sua equipe com o agente de codificação Copilot"
      intro-message: "Neste exercício, você desbloqueará o próximo nível do seu assistente de codificação com IA favorito. Vamos aprender como atribuir tarefas de codificação do Copilot diretamente no GitHub! 💻✨"

  post_next_step_content:
    name: Publicar conteúdo do próximo passo
    runs-on: ubuntu-latest
    needs: [start_exercise]
    env:
      ISSUE_URL: ${{ needs.start_exercise.outputs.issue-url }}

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Obter modelos de resposta
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.6.0

      - name: Construir comentário - adicionar conteúdo da etapa
        id: build-comment
        uses: skills/action-text-variables@v2
        with:
          template-file: ${{ env.STEP_1_FILE }}
          template-vars: |
            login: ${{ github.actor }}
            full_repo_name: ${{ github.repository }}

      - name: Criar comentário - adicionar conteúdo da etapa
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.build-comment.outputs.updated-text }}

      - name: Criar comentário - acompanhando o progresso
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Habilitar workflow da próxima etapa
        run: |
          gh workflow enable "Step 1" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
